builds:
  - binary: slack-docker
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  files:
    - none*
brew:
  github:
    owner: int128
    name: homebrew-slack-docker
  homepage: https://github.com/int128/slack-docker
  description: "Slack integration to notify Docker events"
  test: system "#{bin}/slack-docker --help"
  install: bin.install "slack-docker"